name: Bot Github

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.0-alpha.7
    - name: install module
      run: pip3 install flash requests pystyle
    - name: Run
      run: python main.py
    
